#this is for db connection instead of the generation of beans from db
#there must be a space after each title
server:
  port: 7003


eureka:
  instance:
     hostname: eureka7003.com
  client:
     register-with-eureka: false
     fetch-registry: false
     # service-url.defaultZone: http://${eureka.instance.hostname}:${server.port} # for standalone
     #for cluster
     service-url.defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

