server:
  port: 3344

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jzhan160/microservice-config.git
          username: rogerzjc0113@gmail.com
          password: kinggan123

