#this is for db connection instead of the generation of beans from db
server:
  port: 9527


eureka:
  client:
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: myZuul.com #define the name of micro service
    prefer-ip-address: true

info:
  app.name: microservice
  build.artifactId: $project.artifactId$
  build.version: $project.version$

spring:
  application:
    name: microservice-zuul-gateway


#do not expose the name of micro service
#without this conf, we need to use myZuul.com:9527/microservice-dept/dept/1 to visit
zuul:
  routes:
    mydept.serviceId: microservice-dept
    mydept.path: /mydept/**
  ignored-services: microservice-dept
  #forbid visiting the service by old path
#  using * can ignore all
#  prefix: /jc #must visit by myZuul.com:9527/jc/microservice-dept/dept/1


